services:
  db:
    container_name: weather_postgres_db
    image: bitnami/postgresql:16.1.0-debian-11-r15
    ports:
      - "3000:5432"
    environment:
<<<<<<< HEAD
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db}
=======
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_weather
>>>>>>> 5a74b4af78ccf9db13717d022b35fd4f66136cf1
    volumes:
      - ./postgres/data:/var/lib/postgresql/data