services:
  db:
    container_name: weather_postgres_db
    image: postgres:14.17
    ports:
      - 3000:5432
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${db_user} -d ${db}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  af:
    container_name: airflow_conn
    image: apache/airflow:3.0.0
    ports:
      - 8000:8080
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
      db_user: ${db_user}
      db_pass: ${db_pass}
      db: ${db}
      db_host: db
      db_port: 5432
      auth_api_weather: ${auth_api_weather}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api-request:/opt/airflow/api-request
    depends_on:
      - db
    networks:
      - my_network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  dbt:
    container_name: dbt_conn
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/my_dbt_project:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network
    command: run

networks:
  my_network:
    driver: bridge
